name: libm
version: 1.0.0
dependencies:
  - nightingale-headers
  - nightingale-libc
source:
  url: https://github.com/tyler569/sortix-libm/archive/refs/tags/1.0.tar.gz
  type: tar.gz
  strip_components: 1
patches:
  - 01-remove-build-aux.patch
build:
  build: 'HOST=x86_64-unknown-none CC=clang AR=ar CFLAGS="-target x86_64-unknown-none -I$SYSROOT/usr/include -nostdlib -nostdinc -ffreestanding -D_IEEE_LIBM -D__nightingale__=1 -D_NG_SOURCE=1 -D__USE_SORTIX=1 -D__USE_C=1999" make libm.a'
  install: 'mkdir -p $SYSROOT/usr/lib $SYSROOT/usr/include && cp libm.a $SYSROOT/usr/lib/ && cp -r include/* $SYSROOT/usr/include/'
