.TH READ 2 2020-01-11 "nightingale" "nightingale Programmer's Manual"
.SH NAME
exit - terminate the running process
.SH SYNOPSIS
.nf
.I #include <unistd.h>
.PP
.I noreturn void exit(int status);
.fi
.SH DESCRIPTION
.BR exit ()
terminates the running process, returning the status code
.I status
to the calling process via
.IR waitpid (2) .
.SH RETURN VALUE
.BR exit ()
does not return.
.SH ERRORS
.BR exit ()
can not return an error.
.SH CONFORMING TO
Maybe someday
.SH NOTES
.SH BUGS
.SH EXAMPLE
.EX
#include <unistd.h>

int main() {
    exit(1);
}
.EE
.SH SEE ALSO
.BR execve (2),
.BR exit_group (2),
.BR fork (2)
.SH COLOPHON
.PP
This document is part of the nightingale project.
The project can be found online at
.UR https://github.com/tyler569/nightingale
.UE .
