require 'minitest/autorun'
require 'fileutils'
require 'tmpdir'

ROOT = File.expand_path('..', __dir__)
SCRIPT = File.join(ROOT, 'script', 'generate_syscalls.rb')

class GenerateSyscallsTest < Minitest::Test
  def setup
    @tmpdir = Dir.mktmpdir
    @syscalls = File.join(@tmpdir, 'syscalls.yml')
    @errnos = File.join(@tmpdir, 'errnos.yml')
    File.write(@syscalls, <<~YAML)
      ---
      - number: 1
        name: foo
        frame: false
        return: int
        args:
        - type: int
          name: a
    YAML
    File.write(@errnos, <<~YAML)
      ---
      - number: 1
        name: EFOO
        description: Foo error
    YAML
  end

  def teardown
    FileUtils.remove_entry(@tmpdir)
  end

  def test_generation
    system({'SYSCALLS_YAML' => @syscalls, 'ERRNOS_YAML' => @errnos}, 'ruby', SCRIPT, @tmpdir) or raise 'generation failed'
    consts = File.read(File.join(@tmpdir, 'autogenerated_syscall_consts.h'))
    errnos_h = File.read(File.join(@tmpdir, 'autogenerated_errnos.h'))
    assert_includes(consts, 'NG_FOO')
    assert_includes(errnos_h, 'EFOO')
  end
end