#!/usr/bin/env bash

CODE="fs include kernel libc linker modules sh user x86"

find $CODE \
    -name '*.[ch]' \
    | grep -v 'autogenerated' \
    | xargs clang-format -i

find $CODE -name '*.c' \
    | xargs sed -i 's/if \((.*)\) { \([^;]*;\) }/if \1 \2/'
