all:
	cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=toolchain/CMake/CMakeToolchain.txt -G Ninja
	cmake --build build --config Debug -t iso

clean:
	rm -rf build/{CMakeFiles,autogenerated,kernel,libc,linker,system_root,user,CMakeCache.txt,build.ninja,cmake_install.cmake,packages}
