all:
	cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=toolchain/CMake/CMakeToolchain.txt -G Ninja
	cmake --build build --config Debug -t iso

clean:
	rm -rf build/CMakeFiles build/autogenerated build/kernel build/libc build/linker build/system_root build/user build/CMakeCache.txt build/build.ninja build/cmake_install.cmake
