all:
	cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=toolchain/CMake/CMakeToolchain.txt -G Ninja
	cmake --build build --config Debug -t iso

release:
	cmake -Bbuild-release -H. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=toolchain/CMake/CMakeToolchain.txt -G Ninja
	cmake --build build-release --config Release -t iso

clean:
	rm -rf build/CMakeFiles \
		build/autogenerated \
		build/kernel \
		build/libc \
		build/linker \
		build/sysroot \
		build/iso_root \
		build/user \
		build/CMakeCache.txt \
		build/build.ninja \
		build/cmake_install.cmake \
		build/ngos.iso
