name: nightingale-modules
version: 1.0.0
dependencies: [nightingale-headers]
build:
  configure: cmake -B build/modules -S modules -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$SYSROOT -DCMAKE_TOOLCHAIN_FILE=$(pwd)/toolchain/CMake/CMakeToolchain-kernel.txt
  build: cmake --build build/modules
  install: cmake --install build/modules