#pragma once

#include <dirent.h>
#include <list.h>
#include <ng/dmgr.h>
#include <ng/fs/dentry.h>
#include <ng/fs/file.h>
#include <ng/fs/file_system.h>
#include <ng/fs/proc.h>
#include <ng/fs/vnode.h>
#include <ng/ringbuf.h>
#include <ng/sync.h>
#include <ng/syscall.h>
#include <ng/tty.h>
#include <poll.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <sys/cdefs.h>
#include <sys/socket.h>
#include <sys/syscall_consts.h>
#include <sys/types.h>
