
#pragma once
#ifndef NG_SYSCALLS_H
#define NG_SYSCALLS_H

#include <basic.h>
#include <ng/syscall.h>
#include <ng/thread.h>
#include <ng/uname.h>
#include <ng/cpu.h>
#include <ng/fs.h>
#include <ng/trace.h>
#include <dirent.h>
#include <signal.h>
#include <sys/wait.h>
#include <nightingale.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "autogenerated_syscalls.h"

#endif // NG_SYSCALLS_H

