.TH GETDENTS 2 "2025" "Nightingale" "Nightingale System Calls"
.SH NAME
getdents \- get directory entries
.SH SYNOPSIS
.nf
.B #include <dirent.h>
.PP
.BI "ssize_t getdents(int " fd ", struct dirent *" buf ", size_t " len ");"
.fi
.SH DESCRIPTION
The
.B getdents()
system call reads several
.I dirent
structures from the directory referred to by the open file descriptor
.I fd
into the buffer pointed to by
.IR buf .
The argument
.I len
specifies the size of the buffer.
.PP
The
.I dirent
structure is defined as follows:
.PP
.in +4n
.EX
struct dirent {
    ino_t          d_ino;       /* Inode number */
    off_t          d_off;       /* Offset to next dirent */
    unsigned short d_reclen;    /* Length of this record */
    unsigned char  d_type;      /* Type of file */
    char           d_name[256]; /* Null-terminated filename */
};
.EE
.in
.PP
The only fields in the
.I dirent
structure that are mandated by POSIX are
.IR d_name " and " d_ino .
.SH RETURN VALUE
On success, the number of bytes read is returned.
On end of directory, 0 is returned.
On error, \-1 is returned, and
.I errno
is set to indicate the error.
.SH ERRORS
.TP
.B EBADF
Invalid file descriptor
.IR fd .
.TP
.B ENOTDIR
File descriptor does not refer to a directory.
.TP
.B EFAULT
Argument points outside the calling process's address space.
.SH SEE ALSO
.BR openat (2),
.BR readdir (3)
