#pragma once
#ifndef NG_SYSCALLS_H
#define NG_SYSCALLS_H

#include <basic.h>
#include <dirent.h>
#include <ng/cpu.h>
#include <ng/fs.h>
#include <ng/syscall.h>
#include <ng/thread.h>
#include <ng/trace.h>
#include <signal.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/utsname.h>
#include <sys/wait.h>
#include <syscall_types.h>

#include "autogenerated_syscalls_kernel.h"

#endif // NG_SYSCALLS_H
