#pragma once
#ifndef _ERRNO_H_
#define _ERRNO_H_

#include <stdio.h>

#include "autogenerated_errnos.h"

#define  EAGAIN EWOULDBLOCK

extern const char *errno_names[];

#ifndef _NG
extern int errno;
void perror(const char *const message);
const char *strerror(enum errno_value errno);
#endif // _NG

#endif // _ERRNO_H_
