#!/usr/bin/env bash

CODE="include kernel libc linker user"

export UNCRUSTIFY_CONFIG="uncrustify.cfg"

find $CODE \
    -name '*.[ch]' \
    | grep -v 'autogenerated' \
    | xargs uncrustify --no-backup 2>&1 \
    | grep -B1 -v \
        -e 'Parsing:' \
        -e 'Parsing error precedes' \
        -e 'type is BRACE_CLOSE' \
        -e 'is PP_DEFINED'
