#!/usr/bin/env bash

CODE="include kernel libc linker modules user"

find $CODE \
    -name '*.[ch]' \
    | grep -v 'autogenerated' \
    | xargs clang-format -i

find $CODE -name '*.c' \
    | xargs sed -i 's/if \((.*)\) { \([^;]*;\) }/if \1 \2/'
