.TH UNAME 1 "2025" "Nightingale" "User Commands"
.SH NAME
uname \- print system information
.SH SYNOPSIS
.B uname
.SH DESCRIPTION
Print system information including the operating system name,
release, version, and machine hardware name.
.SH EXAMPLES
.TP
.B uname
Display system information.
.SH NOTES
The Nightingale uname does not support the various option flags
.RB ( \-s ,
.BR \-r ,
.BR \-m ,
etc.) that traditional Unix uname provides.
It always prints all available information.
.SH SEE ALSO
.BR uname (2)
