// This file was AUTOGENERATED by generate_syscalls.rb
// DO NOT EDIT IT

#ifndef _AUTOGENERATED_libc_include_autogenerated_errnos_h_
#define _AUTOGENERATED_libc_include_autogenerated_errnos_h_

enum errno_value {
    SUCCESS = 0,
    ETODO = 1,
    EINVAL = 2,
    EWOULDBLOCK = 3,
    ENOEXEC = 4,
    ENOENT = 5,
    EAFNOSUPPORT = 6,
    EPROTONOSUPPORT = 7,
    ECHILD = 8,
    EPERM = 9,
    EFAULT = 10,
    EBADF = 11,
    ERANGE = 12,
    EACCES = 13,
    ESPIPE = 14,
    EISDIR = 15,
    ESRCH = 16,
    ENOSYS = 17,
    ENOTTY = 18,
    ENOTDIR = 19,
    ECONNREFUSED = 20,
    ENODEV = 21,
    EOPNOTSUPP = 22,
    ENOTSOCK = 23,
    EEXIST = 24,
    ENOTCONN = 25,
    ECONNRESET = 26,
    EDOM = 27,
    EINTR = 28,
    ERRNO_MAX,
};

#endif
