#pragma once
#ifndef _ERRNO_H_
#define _ERRNO_H_

#include <stdio.h>
#include "autogenerated_errnos.h"

#define EAGAIN EWOULDBLOCK

extern const char *errno_names[];

#ifndef __kernel__
extern int errno;
void perror(const char *const message);
char *strerror(int errno);
#endif // __kernel__

#endif // _ERRNO_H_
